### ISSUE TITLE
 The modal window for the currency exchange process is not displayed

### ISSUE THREAD

**Issue by FerretRec** [Aureolaworld/aureola#6] opened 2019-04-12 09:00 UTC

**Comment by FerretRec** [comment] 2019-04-12 10:24
New modal dialog implemented

    <div class="modal uk-modal-container uk-modal" id="successModal">
      <div class="uk-modal-dialog uk-modal-body">
        <button class="uk-modal-close-default modal__close uk-close uk-icon" type="button" data-dismiss="modal"><svg width="14" height="14" viewBox="0 0 14 14" xmlns="http://www.w3.org/2000/svg"><line fill="none" stroke="#000" stroke-width="1.1" x1="1" y1="1" x2="13" y2="13"></line><line fill="none" stroke="#000" stroke-width="1.1" x1="13" y1="1" x2="1" y2="13"></line></svg></button>
        <div class="modal-message" id="modalMessage">
          <div class="uk-text-center modal-message__image"><img src="{% static 'landing/img/message-success.svg' %}" alt="">Успешно</div>
          <div class="modal-message__text uk-text-center" id="messageText"></div>
        </div>
      </div>
    </div>

    <div class="modal uk-modal-container uk-modal" id="failModal">
      <div class="uk-modal-dialog uk-modal-body">
        <button class="uk-modal-close-default modal__close uk-close uk-icon" type="button" data-dismiss="modal"><svg width="14" height="14" viewBox="0 0 14 14" xmlns="http://www.w3.org/2000/svg"><line fill="none" stroke="#000" stroke-width="1.1" x1="1" y1="1" x2="13" y2="13"></line><line fill="none" stroke="#000" stroke-width="1.1" x1="13" y1="1" x2="1" y2="13"></line></svg></button>
        <div class="modal-message" id="modalMessage">
          <div class="uk-text-center modal-message__image"><img src="{% static 'landing/img/message-error.svg' %}" alt="">Ошибка</div>
          <div class="modal-message__text uk-text-center" id="messageText"></div>
        </div>
      </div>
    </div>

**Comment by Ogorodnikova** [comment] 2019-04-16 08:54
Closing this ticket because the problem is resolved

**Closed as completed** 2019-04-16 08:54 UTC
